#' new_create_included.
#'
#' @title do what new_create_included does.
#' @param ex  the dataset ex read from sas
#' @param dm  the dataset dm read from sas
#' @param cr  the dataset cr read from sas
#' @param ds  the dataset ds read from sas
#' @return the included data set
#' @export
#'
#'

new_create_included <- function(ex, dm, cr, ds){

  med <- ex %>% mutate(ptno = as.numeric(CLIENTID),
                       EX_TRT_C = substr(EX_TRT_C, 4, 4),   # get the treatment lable
                       pern = as.numeric(gsub("A|B|C|D|E|F", "", PERIOD)) # remove A or B or C, ect.  equivalent to compress() in SAS
                        )

  medseq <- med %>% arrange(ptno, pern, EX_TRT_C) %>% 
            group_by(ptno, pern, EX_TRT_C) %>% filter(row_number()==1)
  

  # total number of period
  totper <- length(unique(med$pern))
  tottrt <- length(unique(med$EX_TRT_C))

  seqtest <- dcast(medseq, ptno ~ pern, value.var="EX_TRT_C")
  ## add a prefix to the transformed variable
  id0 <- !(names(seqtest)%in% c("ptno", "pern"))
  names(seqtest)[id0] <- paste("dosed_", names(seqtest)[id0], sep = "") 
  
  # add underscores and sets trtflg=* if trt is missing in a period;
  seqtest$seq <- seqtest$trtflg  <- ""
  
   for ( i in 1:totper){
     if (i==1){
       var_id <- which(names(seqtest)==paste("dosed_", i, sep = ""))
       row_id1 <- trimws(seqtest[, var_id]) == ""
       seqtest$seq[row_id1] <- "_"
       seqtest$trtflg[row_id1] <- "*"
       
       seqtest$seq[!row_id1] <- trimws(seqtest[, var_id])
     }
     else{
       var_id <- which(names(seqtest)==paste("dosed_", i, sep = ""))
       row_id1 <- trimws(seqtest[, var_id]) == ""
       seqtest$seq[row_id1] <- paste(trimws(seq), "_")
       seqtest$trtflg[row_id1] <- "*"
       
       seqtest$seq[!row_id1] <- paste(trimws(seq), trimws(seqtest[, var_id]), sep = "")
     }
   }
  seqtest$rseq <- seqtest$seq
  
  
  # add all ptno from the DM dataset to add any ptno that did not get dosed
  dem <- dm %>% mutate(ptno = as.numeric(CLIENTID)) %>% select(ptno, SCRID, CLIENTID)
  
  # additional code to determine if a subject checked in in each period
  chk <- cr %>% mutate(ptno = as.numeric(CLIENTID), chk = "Y",
                       pern = as.numeric(gsub("A|B|C|D|E|F", "", PERIOD))) %>%
                select(ptno, CR_DAT, pern, chk) %>%
                arrange(ptno, pern, chk) %>% 
                group_by(ptno, pern, chk) %>%
                filter(row_number()==1)
  
  # Creating the chkseq variable which is a concatentation of the Y or N    in
  # period 1, the check in for period 2,.....                                 
 
  chkseq <- dcast(chk, ptno + CR_DAT ~ pern, value.var = "chk")
  # add a prefix to the variables generated by pern.
  id1 <- !(names(chkseq)%in% c("ptno", "CR_DAT"))
  names(chkseq)[id1] <- paste("chk_in_", names(chkseq)[id1], sep = "") 
 
  chk_in <- chkseq %>% mutate(chkflg = "")
  detect <-  chk_in %>% select(starts_with("chk_in"))
  # detect$chk_2 <- c(rep("N", 20), rep("Y",6))
  # detect$chk_in_1[10] <- "N"
  id2 <- c()
  for (k in 1:nrow(detect)){
    # if at least one value is something other than "YES"("Y"), the flag should show up.
    id2[k] <- !any(toupper(trimws(detect[k, ])) %in%  c("YES", "Y")) 
  }
  chk_in$chkflg[id2] <- "*"
  
  dis <- ds %>% mutate(ptno = as.numeric(CLIENTID))
  ds_ans_exist <- any(names(dis) %in% "DS_ANS")
  if(ds_ans_exist){
    dis$comp <- ifelse(dis$DS_ANS %in% c("YES", "Y"), "Y", "")
  } else{
    dis$comp <- ""
  }
  names(dis)[ncol(dis)] <- paste("comp_", totper, sep = "")
  
  dis <- dis %>% select(ptno, starts_with("comp_"))  # the SAS code has DS_ANS included
  
  
  seqtest1 <- full_join(seqtest %>% arrange(ptno), 
                        full_join(dem %>% arrange(ptno),
                            full_join(chk_in %>% arrange(ptno), 
                                      dis %>% arrange(ptno)))) %>%
              mutate(flag = "")
  id3 <- seqtest1$trtflg != "" | seqtest1$chkflg != ""  # the SAS code has DS_ANS included
  seqtest1$flag[id3] <- "*"
  
  seqtest2 <- seqtest1 %>% select(-trtflg, -chkflg) %>% 
              mutate(compprot = ifelse(flag != "",  "Y", "N"), 
                     safeanal = "Y",
                     pkanal = ifelse(flag != "", "Y", "N"))
  
  names(seqtest2) <- toupper(names(seqtest2))
  return(seqtest2)
}


